// Syntari AI IDE - Editor Configuration Constants
// Extracted from CodeEditor.tsx for better maintainability

export const EDITOR_OPTIONS = {
  fontSize: 14,
  fontFamily: "'Fira Code', 'Monaco', 'Menlo', 'Ubuntu Mono', monospace",
  lineNumbers: 'on' as const,
  roundedSelection: false,
  scrollBeyondLastLine: false,
  readOnly: false,
  cursorStyle: 'line' as const,
  automaticLayout: true,
  wordWrap: 'on' as const,
  theme: 'syntari-dark',
  minimap: {
    enabled: true,
    side: 'right' as const,
    scale: 1,
    showSlider: 'mouseover' as const,
  },
  bracketPairColorization: {
    enabled: true,
  },
  guides: {
    indentation: true,
    bracketPairs: true,
  },
  suggest: {
    enabled: true,
    showKeywords: true,
    showSnippets: true,
    showFunctions: true,
    showConstructors: true,
    showFields: true,
    showVariables: true,
    showClasses: true,
    showStructs: true,
    showInterfaces: true,
    showModules: true,
    showProperties: true,
    showEvents: true,
    showOperators: true,
    showUnits: true,
    showValues: true,
    showConstants: true,
    showEnums: true,
    showEnumMembers: true,
    showReferences: true,
    showFolders: true,
    showTypeParameters: true,
    showIssues: true,
    showUsers: true,
    showColors: true,
  },
  quickSuggestions: {
    other: true,
    comments: true,
    strings: true,
  },
  parameterHints: {
    enabled: true,
  },
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: 'on' as const,
  accessibilitySupport: 'auto' as const,
  autoIndent: 'full' as const,
  codeLens: true,
  colorDecorators: true,
  contextmenu: true,
  copyWithSyntaxHighlighting: true,
  dragAndDrop: true,
  find: {
    addExtraSpaceOnTop: false,
    autoFindInSelection: 'never' as const,
    seedSearchStringFromSelection: 'always' as const,
  },
  folding: true,
  foldingStrategy: 'auto' as const,
  fontLigatures: true,
  formatOnPaste: true,
  formatOnType: true,
  glyphMargin: true,
  hideCursorInOverviewRuler: false,
  highlightActiveIndentGuide: true,
  links: true,
  mouseWheelZoom: true,
  multiCursorMergeOverlapping: true,
  multiCursorModifier: 'alt' as const,
  occurrencesHighlight: 'singleFile' as const,
  overviewRulerBorder: true,
  renderControlCharacters: false,
  renderIndentGuides: true,
  renderLineHighlight: 'line' as const,
  renderWhitespace: 'selection' as const,
  revealHorizontalRightPadding: 30,
  scrollbar: {
    vertical: 'visible' as const,
    horizontal: 'visible' as const,
    arrowSize: 11,
    useShadows: true,
    verticalHasArrows: false,
    horizontalHasArrows: false,
    verticalScrollbarSize: 14,
    horizontalScrollbarSize: 14,
    verticalSliderSize: 14,
    horizontalSliderSize: 14,
  },
  selectOnLineNumbers: true,
  selectionClipboard: false,
  selectionHighlight: true,
  showFoldingControls: 'mouseover' as const,
  smoothScrolling: true,
  snippetSuggestions: 'top' as const,
  stickyTabStops: false,
  tabCompletion: 'on' as const,
  useTabStops: true,
  wordBasedSuggestions: 'currentDocument' as const,
  wordSeparators: '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?',
  wordWrapBreakAfterCharacters: '\t})]?|/&.,;¢°′″‰℃、。｡､￠，．：；？！％・･ゝゞヽヾーァィゥェォッャュョヮヵヶぁぃぅぇぉっゃゅょゎゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇺㇻㇼㇽㇾㇿ々〻ｧｨｩｪｫｬｭｮｯｰ"〉》」』】〕）］｝｠',
  wordWrapBreakBeforeCharacters: '([{\'\"〈《「『【〔（［｛｟',
  wrappingIndent: 'none' as const,
  wrappingStrategy: 'simple' as const,
};

export const LANGUAGE_MAP: Record<string, string> = {
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.rs': 'rust',
  '.py': 'python',
  '.md': 'markdown',
  '.json': 'json',
  '.html': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.xml': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'ini',
  '.ini': 'ini',
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.fish': 'shell',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.sql': 'sql',
  '.go': 'go',
  '.java': 'java',
  '.kt': 'kotlin',
  '.swift': 'swift',
  '.c': 'c',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.cc': 'cpp',
  '.h': 'c',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.cs': 'csharp',
  '.php': 'php',
  '.rb': 'ruby',
  '.lua': 'lua',
  '.dart': 'dart',
  '.r': 'r',
  '.jl': 'julia',
  '.scala': 'scala',
  '.clj': 'clojure',
  '.elm': 'elm',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.fs': 'fsharp',
  '.fsx': 'fsharp',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.nim': 'nim',
  '.nims': 'nim',
  '.cr': 'crystal',
  '.zig': 'zig',
  '.v': 'verilog',
  '.sv': 'systemverilog',
  '.vhd': 'vhdl',
  '.vhdl': 'vhdl',
  '.dockerfile': 'dockerfile',
  '.Dockerfile': 'dockerfile',
  '.tex': 'latex',
  '.cls': 'latex',
  '.sty': 'latex',
  '.bib': 'bibtex',
};

export const FILE_ICONS: Record<string, string> = {
  '.js': '🟨',
  '.jsx': '⚛️',
  '.ts': '🔷',
  '.tsx': '⚛️',
  '.rs': '🦀',
  '.py': '🐍',
  '.md': '📝',
  '.json': '📋',
  '.html': '🌐',
  '.css': '🎨',
  '.scss': '🎨',
  '.sass': '🎨',
  '.less': '🎨',
  '.xml': '📄',
  '.yaml': '⚙️',
  '.yml': '⚙️',
  '.toml': '⚙️',
  '.ini': '⚙️',
  '.sh': '💻',
  '.bash': '💻',
  '.zsh': '💻',
  '.fish': '💻',
  '.ps1': '💻',
  '.sql': '🗄️',
  '.go': '🐹',
  '.java': '☕',
  '.kt': '🟣',
  '.swift': '🐦',
  '.c': '📘',
  '.cpp': '📘',
  '.h': '📘',
  '.hpp': '📘',
  '.cs': '💜',
  '.php': '🐘',
  '.rb': '💎',
  '.lua': '🌙',
  '.dart': '🎯',
  '.r': '📊',
  '.dockerfile': '🐳',
  '.Dockerfile': '🐳',
}; 